export const AIRPORT = {
  ADD_AIRPORT: "ADD_AIRPORT",
  DELETE_AIRPORT: "DELETE_AIRPORT",
  MODIFY_AIRPORT: "MODIFY_AIRPORT",
};

export const AIRLINE = {
  ADD_AIRLINE: "ADD_AIRLINE",
  DELETE_AIRLINE: "DELETE_AIRLINE",
  MODIFY_AIRLINE: "MODIFY_AIRLINE",
};

export const FLIGHT = {
  ADD_FLIGHT: "ADD_FLIGHT",
  DELETE_FLIGHT: "DELETE_FLIGHT",
  MODIFY_FLIGHT: "MODIFY_FLIGHT",

  DELETE_FLIGHTS_ON_DELETED_AIRPORT: "DELETE_FLIGHTS_ON_DELETED_AIRPORT",
  DELETE_FLIGHTS_ON_DELETED_AIRLINE: "DELETE_FLIGHTS_ON_DELETED_AIRLINE",

  ADD_SECTION: "ADD_SECTION",
  DELETE_SECTION: "DELETE_SECTION",

  BOOK_SEAT: "BOOK_SEAT",
  UNBOOK_SEAT: "UNBOOK_SEAT",
};
