export const AIRPORT = {
  ADD_AIRPORT: "ADD_AIRPORT",
  DELETE_AIRPORT: "DELETE_AIRPORT",
  MODIFY_AIRPORT: "MODIFY_AIRPORT",
};

export const AIRLINE = {
  ADD_AIRLINE: "ADD_AIRLINE",
  DELETE_AIRLINE: "DELETE_AIRLINE",
  MODIFY_AIRLINE: "MODIFY_AIRLINE",
};
