// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAbsApi.Data;

namespace WebAbsApi.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20210821170243_AddAirportAirlineFlights2.0")]
    partial class AddAirportAirlineFlights20
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAbsApi.Data.Airline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("Airlines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "DELTA"
                        },
                        new
                        {
                            Id = 2,
                            Name = "SSSKY"
                        },
                        new
                        {
                            Id = 3,
                            Name = "FLYSS"
                        },
                        new
                        {
                            Id = 4,
                            Name = "ARB"
                        },
                        new
                        {
                            Id = 5,
                            Name = "WIZZ"
                        });
                });

            modelBuilder.Entity("WebAbsApi.Data.Airport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("Airports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "AAY"
                        },
                        new
                        {
                            Id = 2,
                            Name = "ABA"
                        },
                        new
                        {
                            Id = 3,
                            Name = "MAC"
                        },
                        new
                        {
                            Id = 4,
                            Name = "FSD"
                        },
                        new
                        {
                            Id = 5,
                            Name = "ZAG"
                        });
                });

            modelBuilder.Entity("WebAbsApi.Data.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AirlineId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<string>("FlightNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OriginId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AirlineId");

                    b.HasIndex("DestinationId");

                    b.HasIndex("OriginId");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AirlineId = 2,
                            Date = new DateTime(2021, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationId = 5,
                            FlightNumber = "111111111",
                            OriginId = 1
                        },
                        new
                        {
                            Id = 2,
                            AirlineId = 2,
                            Date = new DateTime(2021, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationId = 5,
                            FlightNumber = "211111111",
                            OriginId = 1
                        });
                });

            modelBuilder.Entity("WebAbsApi.Data.Flight", b =>
                {
                    b.HasOne("WebAbsApi.Data.Airline", "Airline")
                        .WithMany("Flights")
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAbsApi.Data.Airport", "DestinationAirport")
                        .WithMany("DestinationToFlights")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.HasOne("WebAbsApi.Data.Airport", "OriginAirport")
                        .WithMany("OriginToFlights")
                        .HasForeignKey("OriginId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.Navigation("Airline");

                    b.Navigation("DestinationAirport");

                    b.Navigation("OriginAirport");
                });

            modelBuilder.Entity("WebAbsApi.Data.Airline", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("WebAbsApi.Data.Airport", b =>
                {
                    b.Navigation("DestinationToFlights");

                    b.Navigation("OriginToFlights");
                });
#pragma warning restore 612, 618
        }
    }
}
