// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAbsApi.Data;

namespace WebAbsApi.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "3b4cc535-ec11-4ceb-a073-c5d2edea5f4e",
                            ConcurrencyStamp = "20aec54c-82e0-41dc-98b2-25ffccae25a6",
                            Name = "User",
                            NormalizedName = "USER"
                        },
                        new
                        {
                            Id = "3c0a4c9c-d5e7-4d51-98bc-c4766f3a5998",
                            ConcurrencyStamp = "203fbbe3-18ac-406a-8753-a22ac2d0da92",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("WebAbsApi.Data.Airline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("Airlines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "DELTA"
                        },
                        new
                        {
                            Id = 2,
                            Name = "SSSKY"
                        },
                        new
                        {
                            Id = 3,
                            Name = "FLYSS"
                        },
                        new
                        {
                            Id = 4,
                            Name = "ARB"
                        },
                        new
                        {
                            Id = 5,
                            Name = "WIZZ"
                        });
                });

            modelBuilder.Entity("WebAbsApi.Data.Airport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasFilter("[Name] IS NOT NULL");

                    b.ToTable("Airports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "AAY"
                        },
                        new
                        {
                            Id = 2,
                            Name = "ABA"
                        },
                        new
                        {
                            Id = 3,
                            Name = "MAC"
                        },
                        new
                        {
                            Id = 4,
                            Name = "FSD"
                        },
                        new
                        {
                            Id = 5,
                            Name = "ZAG"
                        });
                });

            modelBuilder.Entity("WebAbsApi.Data.ApiUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("WebAbsApi.Data.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AirlineId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DestinationId")
                        .HasColumnType("int");

                    b.Property<string>("FlightNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("OriginId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AirlineId");

                    b.HasIndex("DestinationId");

                    b.HasIndex("FlightNumber")
                        .IsUnique()
                        .HasFilter("[FlightNumber] IS NOT NULL");

                    b.HasIndex("OriginId");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AirlineId = 2,
                            Date = new DateTime(2021, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationId = 5,
                            FlightNumber = "111111111",
                            OriginId = 1
                        },
                        new
                        {
                            Id = 2,
                            AirlineId = 2,
                            Date = new DateTime(2021, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DestinationId = 1,
                            FlightNumber = "211111111",
                            OriginId = 5
                        });
                });

            modelBuilder.Entity("WebAbsApi.Data.FlightSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<string>("SeatClass")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("FlightId", "SeatClass")
                        .IsUnique()
                        .HasFilter("[SeatClass] IS NOT NULL");

                    b.ToTable("FlightSections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FlightId = 1,
                            SeatClass = "FIRST"
                        },
                        new
                        {
                            Id = 2,
                            FlightId = 1,
                            SeatClass = "ECONOMY"
                        },
                        new
                        {
                            Id = 3,
                            FlightId = 2,
                            SeatClass = "BUSINESS"
                        });
                });

            modelBuilder.Entity("WebAbsApi.Data.Seat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Column")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("FlightSectionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsBooked")
                        .HasColumnType("bit");

                    b.Property<string>("Row")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("FlightSectionId", "Row", "Column")
                        .IsUnique()
                        .HasFilter("[Row] IS NOT NULL AND [Column] IS NOT NULL");

                    b.ToTable("Seats");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Column = "A",
                            FlightSectionId = 1,
                            IsBooked = false,
                            Row = "1"
                        },
                        new
                        {
                            Id = 2,
                            Column = "B",
                            FlightSectionId = 1,
                            IsBooked = false,
                            Row = "1"
                        },
                        new
                        {
                            Id = 3,
                            Column = "C",
                            FlightSectionId = 1,
                            IsBooked = false,
                            Row = "1"
                        },
                        new
                        {
                            Id = 4,
                            Column = "D",
                            FlightSectionId = 1,
                            IsBooked = false,
                            Row = "1"
                        },
                        new
                        {
                            Id = 5,
                            Column = "A",
                            FlightSectionId = 1,
                            IsBooked = false,
                            Row = "2"
                        },
                        new
                        {
                            Id = 6,
                            Column = "B",
                            FlightSectionId = 1,
                            IsBooked = false,
                            Row = "2"
                        },
                        new
                        {
                            Id = 7,
                            Column = "C",
                            FlightSectionId = 1,
                            IsBooked = false,
                            Row = "2"
                        },
                        new
                        {
                            Id = 8,
                            Column = "D",
                            FlightSectionId = 1,
                            IsBooked = false,
                            Row = "2"
                        },
                        new
                        {
                            Id = 9,
                            Column = "A",
                            FlightSectionId = 1,
                            IsBooked = false,
                            Row = "3"
                        },
                        new
                        {
                            Id = 10,
                            Column = "B",
                            FlightSectionId = 1,
                            IsBooked = false,
                            Row = "3"
                        },
                        new
                        {
                            Id = 11,
                            Column = "C",
                            FlightSectionId = 1,
                            IsBooked = false,
                            Row = "3"
                        },
                        new
                        {
                            Id = 12,
                            Column = "D",
                            FlightSectionId = 1,
                            IsBooked = false,
                            Row = "3"
                        },
                        new
                        {
                            Id = 13,
                            Column = "A",
                            FlightSectionId = 1,
                            IsBooked = false,
                            Row = "4"
                        },
                        new
                        {
                            Id = 14,
                            Column = "B",
                            FlightSectionId = 1,
                            IsBooked = false,
                            Row = "4"
                        },
                        new
                        {
                            Id = 15,
                            Column = "C",
                            FlightSectionId = 1,
                            IsBooked = false,
                            Row = "4"
                        },
                        new
                        {
                            Id = 16,
                            Column = "D",
                            FlightSectionId = 1,
                            IsBooked = false,
                            Row = "4"
                        },
                        new
                        {
                            Id = 17,
                            Column = "A",
                            FlightSectionId = 1,
                            IsBooked = false,
                            Row = "5"
                        },
                        new
                        {
                            Id = 18,
                            Column = "B",
                            FlightSectionId = 1,
                            IsBooked = false,
                            Row = "5"
                        },
                        new
                        {
                            Id = 19,
                            Column = "C",
                            FlightSectionId = 1,
                            IsBooked = false,
                            Row = "5"
                        },
                        new
                        {
                            Id = 20,
                            Column = "D",
                            FlightSectionId = 1,
                            IsBooked = false,
                            Row = "5"
                        });
                });

            modelBuilder.Entity("WebAbsApi.Data.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<int>("FlightSectionId")
                        .HasColumnType("int");

                    b.Property<int>("SeatId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.HasIndex("FlightSectionId");

                    b.HasIndex("SeatId")
                        .IsUnique();

                    b.HasIndex("UserId", "FlightId", "FlightSectionId", "SeatId")
                        .IsUnique()
                        .HasFilter("[UserId] IS NOT NULL");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("WebAbsApi.Data.ApiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("WebAbsApi.Data.ApiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAbsApi.Data.ApiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("WebAbsApi.Data.ApiUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebAbsApi.Data.Flight", b =>
                {
                    b.HasOne("WebAbsApi.Data.Airline", "Airline")
                        .WithMany("Flights")
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAbsApi.Data.Airport", "DestinationAirport")
                        .WithMany("DestinationToFlights")
                        .HasForeignKey("DestinationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WebAbsApi.Data.Airport", "OriginAirport")
                        .WithMany("OriginToFlights")
                        .HasForeignKey("OriginId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Airline");

                    b.Navigation("DestinationAirport");

                    b.Navigation("OriginAirport");
                });

            modelBuilder.Entity("WebAbsApi.Data.FlightSection", b =>
                {
                    b.HasOne("WebAbsApi.Data.Flight", "Flight")
                        .WithMany("FlightSections")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("WebAbsApi.Data.Seat", b =>
                {
                    b.HasOne("WebAbsApi.Data.FlightSection", "FlightSection")
                        .WithMany("Seats")
                        .HasForeignKey("FlightSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlightSection");
                });

            modelBuilder.Entity("WebAbsApi.Data.Ticket", b =>
                {
                    b.HasOne("WebAbsApi.Data.Flight", "Flight")
                        .WithMany("Tickets")
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebAbsApi.Data.FlightSection", "FlightSection")
                        .WithMany("Tickets")
                        .HasForeignKey("FlightSectionId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.HasOne("WebAbsApi.Data.Seat", "Seat")
                        .WithOne("Ticket")
                        .HasForeignKey("WebAbsApi.Data.Ticket", "SeatId")
                        .OnDelete(DeleteBehavior.ClientNoAction)
                        .IsRequired();

                    b.HasOne("WebAbsApi.Data.ApiUser", "ApiUser")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("ApiUser");

                    b.Navigation("Flight");

                    b.Navigation("FlightSection");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("WebAbsApi.Data.Airline", b =>
                {
                    b.Navigation("Flights");
                });

            modelBuilder.Entity("WebAbsApi.Data.Airport", b =>
                {
                    b.Navigation("DestinationToFlights");

                    b.Navigation("OriginToFlights");
                });

            modelBuilder.Entity("WebAbsApi.Data.Flight", b =>
                {
                    b.Navigation("FlightSections");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("WebAbsApi.Data.FlightSection", b =>
                {
                    b.Navigation("Seats");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("WebAbsApi.Data.Seat", b =>
                {
                    b.Navigation("Ticket");
                });
#pragma warning restore 612, 618
        }
    }
}
